= Vert.x Service Resolver

The Service Resolver library is a plugin that lets Vert.x clients call services using logical service names instead of network addresses. The service resolver is also able to perform client side load balancing with the usual strategies.

== Getting started with the Vert.x HTTP Client

Given a resolver, you can configure a Vert.x HTTP Client to use it thanks to an {@link io.vertx.core.http.HttpClientBuilder}.

[source,java]
----
{@link examples.ServiceResolverExamples#configuringHttpClient}
----

A service is addressed with a `{@link io.vertx.serviceresolver.ServiceAddress}` instead of a `{@link io.vertx.core.net.SocketAddress}`.

[source,java]
----
{@link examples.ServiceResolverExamples#usingHttpClient}
----

== Getting started with the Vert.x Web Client

Given a resolver, you can configure a Vert.x Web Client to use it thanks to an {@link io.vertx.core.http.HttpClientBuilder}.

[source,java]
----
HttpClient httpClient = vertx.httpClientBuilder()
  .withAddressResolver(resolver)
  .build();
WebClient webClient = WebClient.wrap(httpClient);
----

A service is addressed with a `{@link io.vertx.serviceresolver.ServiceAddress}`.

[source,java]
----
ServiceAddress serviceAddress = ServiceAddress.create("the-service");

Future<HttpResponse<Buffer>> future = webClient
  .request(HttpMethod.GET, new RequestOptions().setServer(serviceAddress))
  .send();
----

=== Client side load balancing

The default load balancing behavior is _round-robin_, you can change the load balancer to use:

[source,java]
----
{@link examples.ServiceResolverExamples#configuringHttpClientWithLoadBalancing}
----

== Kubernetes resolver

The Kubernetes resolver locates services within a Kubernetes cluster.

[IMPORTANT]
====
The Kubernetes resolver requires the `endpoints` resource to be accessible using the service account configured for the pod.

Here is an example configuration of role and role binding for the `default` service account:

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: observe-endpoints
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: observe-endpoints
  namespace: default
roleRef:
  kind: Role
  name: observe-endpoints
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
----
====

[source,java]
----
{@link examples.ServiceResolverExamples#usingKubernetesResolver}
----

The default resolver options values are loaded from the pod environment
- `KUBERNETES_SERVICE_HOST`
- `KUBERNETES_SERVICE_PORT`
- `/var/run/secrets/kubernetes.io/serviceaccount/token`
- `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`
- `/var/run/secrets/kubernetes.io/serviceaccount/namespace`

You can override these settings.

[source,java]
----
{@link examples.ServiceResolverExamples#configuringKubernetesResolver}
----

== SRV resolver

The SRV resolver uses DNS SRV records to resolve and locate services.

[source,java]
----
{@link examples.ServiceResolverExamples#configuringSRVResolver}
----
