= Vert.x Service Resolver

The Service Resolver library is a plugin that lets Vert.x clients call services using logical service names instead of network addresses. The service resolver is also able to perform client side load balancing with the usual strategies.

You can use a service resolver as a client to query a resolver or integrated natively with a Vert.x client.

== Service resolver client

You can query a service resolver with the service resolver client.

[source,java]
----
{@link examples.ServiceResolverExamples#serviceResolverClient}
----

You can also let the load balancer select nodes

[source,java]
----
{@link examples.ServiceResolverExamples#serviceResolverClient}
----

== Client integration

The service resolver is integrated with the Vert.x HTTP and Web clients.

=== Getting started with the Vert.x HTTP Client

Given a resolver, you can configure a Vert.x HTTP Client to use it thanks to an {@link io.vertx.core.http.HttpClientBuilder}.

[source,java]
----
{@link examples.ServiceResolverExamples#configuringHttpClient}
----

A service is addressed with a `{@link io.vertx.serviceresolver.ServiceAddress}` instead of a `{@link io.vertx.core.net.SocketAddress}`.

[source,java]
----
{@link examples.ServiceResolverExamples#usingHttpClient}
----

=== Getting started with the Vert.x Web Client

Given a resolver, you can configure a Vert.x Web Client to use it thanks to an {@link io.vertx.core.http.HttpClientBuilder}.

[source,java]
----
HttpClient httpClient = vertx.httpClientBuilder()
  .withAddressResolver(resolver)
  .build();
WebClient webClient = WebClient.wrap(httpClient);
----

A service is addressed with a `{@link io.vertx.serviceresolver.ServiceAddress}`.

[source,java]
----
ServiceAddress serviceAddress = ServiceAddress.create("the-service");

Future<HttpResponse<Buffer>> future = webClient
  .request(HttpMethod.GET, new RequestOptions().setServer(serviceAddress))
  .send();
----

=== Client side load balancing

The default load balancing behavior is _round-robin_, you can change the load balancer to use:

[source,java]
----
{@link examples.ServiceResolverExamples#configuringHttpClientWithLoadBalancing}
----

== Service resolver implementations

The service resolver integrates with a few discovery services such as Kubernetes and DNS SRV records.

=== Kubernetes resolver

The Kubernetes resolver locates services within a Kubernetes cluster.

[IMPORTANT]
====
The Kubernetes resolver requires the `endpoints` resource to be accessible using the service account configured for the pod.

Here is an example configuration of role and role binding for the `default` service account:

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: observe-endpoints
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: observe-endpoints
  namespace: default
roleRef:
  kind: Role
  name: observe-endpoints
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
----
====

[source,java]
----
{@link examples.ServiceResolverExamples#usingKubernetesResolver}
----

The default resolver options values are loaded from the pod environment
- `KUBERNETES_SERVICE_HOST`
- `KUBERNETES_SERVICE_PORT`
- `/var/run/secrets/kubernetes.io/serviceaccount/token`
- `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`
- `/var/run/secrets/kubernetes.io/serviceaccount/namespace`

You can override these settings.

You can deal with ephemeral tokens using the {@link io.vertx.serviceresolver.kube.KubeResolver#tokenProvider}.

[source,java]
----
{@link examples.ServiceResolverExamples#usingKubernetesTokenProvider}
----

The resolver calls the provider when it needs a fresh token. The token is cached by the resolver until it is detetected
stale by the resolver (upon a `401` server response code).

==== Matching specific service ports

When a service exposes more than one port, the resolver retains only a single port, it might not be the expected port.

You can build a specific service address for a given service port number.

[source,java]
----
{@link examples.ServiceResolverExamples#servicePortNumberMatching}
----

Or a given service port name.

[source,java]
----
{@link examples.ServiceResolverExamples#servicePortNameMatching}
----

=== SRV resolver

The SRV resolver uses DNS SRV records to resolve and locate services.

[source,java]
----
{@link examples.ServiceResolverExamples#configuringSRVResolver}
----
